### PR TITLE
Feature/my segments

### PR DESCRIPTION
**Pull request by JKHeadley**
This should fix some of the routing issues that we have which will allow us to move forward with https://github.com/cusac/mbt.guide/pull/86. 

## Summary of changes

- `/` route now set to a home page that displays the landing page
- Previous default route `/` now set to `/videos` route
- Previous search route `/search` now set to `/segments`
- Added new `/my-segments` route

**NOTE**: Some of these changes might conflict with what has been done on https://github.com/cusac/mbt.guide/pull/86. Once this PR is merged, I will make sure to merge master into https://github.com/cusac/mbt.guide/pull/86 so that changes made in https://github.com/cusac/mbt.guide/pull/86 are not lost.

### CODE REVIEW

**Comment by oormicreations** [comment]
@JKHeadley My segments is awesome!

**Review by oormicreations — CHANGES_REQUESTED** [review]
@JKHeadley My segments is awesome!
Other links on sidebar work only when there are cookies. 
They show nothing when the user visits the site for first time. (Open in incognito mode to check). Navigation is also erratic.
My request is - users  should see something instead of a blank page when they visit for the first time.

**Comment by JKHeadley** [comment]
Thanks for being so thorough @oormicreations ! I pushed an update that should take care of those issues. If you could check one more time to make sure I haven't missed anything then hopefully we can move forward!

**Review by oormicreations — APPROVED** [review]
@JKHeadley Its perfect now. No blank pages. Yes we can go ahead, everyone is waiting for the big update.

**Pull request merged**
